
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.20.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace BetaOneCLI {
    using System;
    using Terminal.Gui;
    
    
    public partial class WelcomeScreen : Terminal.Gui.Window {
        
        private Terminal.Gui.ColorScheme greyOnBlack2;
        
        private Terminal.Gui.ColorScheme blueOnBlack;
        
        private Terminal.Gui.ColorScheme whiteOnBlack;
        
        private Terminal.Gui.ColorScheme greyOnBlack;
        
        private Terminal.Gui.Wizard welcomeScreen;
        
        private Terminal.Gui.Label label;
        
        private Terminal.Gui.Label label2;
        
        private Terminal.Gui.TextField field_login;
        
        private Terminal.Gui.Label label3;
        
        private Terminal.Gui.TextField fieldPassword;
        
        private void InitializeComponent() {
            this.fieldPassword = new Terminal.Gui.TextField();
            this.label3 = new Terminal.Gui.Label();
            this.field_login = new Terminal.Gui.TextField();
            this.label2 = new Terminal.Gui.Label();
            this.label = new Terminal.Gui.Label();
            this.welcomeScreen = new Terminal.Gui.Wizard();
            this.greyOnBlack2 = new Terminal.Gui.ColorScheme();
            this.greyOnBlack2.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.greyOnBlack2.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.greyOnBlack2.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.DarkGray);
            this.greyOnBlack2.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.DarkGray);
            this.greyOnBlack2.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.blueOnBlack = new Terminal.Gui.ColorScheme();
            this.blueOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightBlue, Terminal.Gui.Color.Black);
            this.blueOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Cyan, Terminal.Gui.Color.Black);
            this.blueOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightBlue, Terminal.Gui.Color.BrightYellow);
            this.blueOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Cyan, Terminal.Gui.Color.BrightYellow);
            this.blueOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.Black);
            this.whiteOnBlack = new Terminal.Gui.ColorScheme();
            this.whiteOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.Black);
            this.whiteOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.Black);
            this.whiteOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.Black);
            this.whiteOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.Black);
            this.whiteOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.Black);
            this.greyOnBlack = new Terminal.Gui.ColorScheme();
            this.greyOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.greyOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.greyOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.DarkGray);
            this.greyOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.DarkGray);
            this.greyOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.ColorScheme = this.greyOnBlack2;
            this.Modal = false;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.BorderBrush = Terminal.Gui.Color.Blue;
            this.Border.Effect3D = false;
            this.Border.Effect3DBrush = null;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "";
            this.welcomeScreen.Width = 70;
            this.welcomeScreen.Height = 20;
            this.welcomeScreen.X = Pos.Center();
            this.welcomeScreen.Y = Pos.Center();
            this.welcomeScreen.ColorScheme = this.greyOnBlack2;
            this.welcomeScreen.Modal = false;
            this.welcomeScreen.Data = "welcomeScreen";
            this.welcomeScreen.Text = "";
            this.welcomeScreen.Border.BorderStyle = Terminal.Gui.BorderStyle.None;
            this.welcomeScreen.Border.BorderBrush = Terminal.Gui.Color.Blue;
            this.welcomeScreen.Border.Effect3D = false;
            this.welcomeScreen.Border.Effect3DBrush = null;
            this.welcomeScreen.Border.DrawMarginFrame = false;
            this.welcomeScreen.TextAlignment = Terminal.Gui.TextAlignment.Justified;
            this.welcomeScreen.Title = "WELCOME";
            this.Add(this.welcomeScreen);
            this.label.Width = 54;
            this.label.Height = 3;
            this.label.X = 7;
            this.label.Y = 1;
            this.label.ColorScheme = this.greyOnBlack2;
            this.label.Data = "label";
            this.label.Text = "Welcome to BETA ONE MESSENGER";
            this.label.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.welcomeScreen.Add(this.label);
            this.label2.Width = 9;
            this.label2.Height = 1;
            this.label2.X = 7;
            this.label2.Y = 6;
            this.label2.Data = "label2";
            this.label2.Text = "Login";
            this.label2.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.welcomeScreen.Add(this.label2);
            this.field_login.Width = Dim.Percent(80f);
            this.field_login.Height = 1;
            this.field_login.X = Pos.Center();
            this.field_login.Y = 7;
            this.field_login.Secret = false;
            this.field_login.Data = "field_login";
            this.field_login.Text = "";
            this.field_login.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.welcomeScreen.Add(this.field_login);
            this.label3.Width = 2;
            this.label3.Height = 1;
            this.label3.X = 7;
            this.label3.Y = 9;
            this.label3.Data = "label3";
            this.label3.Text = "Password";
            this.label3.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.welcomeScreen.Add(this.label3);
            this.fieldPassword.Width = Dim.Percent(80f);
            this.fieldPassword.Height = 1;
            this.fieldPassword.X = Pos.Center();
            this.fieldPassword.Y = 10;
            this.fieldPassword.Secret = false;
            this.fieldPassword.Data = "fieldPassword";
            this.fieldPassword.Text = "";
            this.fieldPassword.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.welcomeScreen.Add(this.fieldPassword);
        }
    }
}
